language: node_js
node_js:
  - "6"
  - "5"
  - "4"
install:
  - npm install coveralls
  - npm install
script:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage